### ISSUE TITLE
Please make a tag for 2.8.2 or 2.8.3

### ISSUE THREAD

**Issue by ArsenShnurkov** [mrward/nuget#1]
Ebuild's require a tarball with sources to be downloaded. The way to create such a tarbal is to make tag.

I am not sure about exact version (2.8.2 or 2.8.3) because of this bug - https://github.com/gentoo/dotnet/issues/33 . But in your version of sources may be any version of NuGet will work, I don't know.

right now you have 3.0.0-preview and 2.7.3 tags. And I don't know what to choose for monodevelop 5.7.0

**Comment by mrward** [comment]
I have added two tags: 
- Release-2.8.1-MonoDevelop
- Release-2.8.3-MonoDevelop

If you are building MonoDevelop 5.7 you will need to use Release-2.8.1-MonoDevelop. NuGet 2.8.3
